services:
  netbox-agent:
    image: static74/netbox-agent:latest
    container_name: netbox-agent
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile   
    ports:
      - "8501:8501"